# Generated by Django 5.0.3 on 2024-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
