# Generated by Django 5.0.3 on 2024-03-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_', '0006_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
