# Generated by Django 5.0.3 on 2024-03-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_', '0010_alter_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
